version: '3.8'

services:
  mysql:
    image: mysql:latest
    container_name: go-chzzk
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: chatting
      MYSQL_DATABASE: chatting
      MYSQL_USER: chatting
      MYSQL_PASSWORD: chatting
    ports:
      - "3306:3306"
    volumes:
      - mysql-data:/var/lib/mysql

volumes:
  mysql-data: